version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  send-message:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: node telegram_bot.js
workflows:
  send-message:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - send-message:
          context:
            - whale-bot
